# --------- Etapa 1: Build y Dependencias ---------
FROM node:20-alpine AS builder

WORKDIR /app

# Copiamos descriptores de dependencias primero para aprovechar cache
COPY package*.json ./

# Instalación limpia para entorno CI/Producción
RUN npm ci

# Copiar el código fuente completo
COPY . .
RUN npm run build

# Construimos la aplicación
RUN npm run build 

# --------- Etapa 2: Producción con Nginx ---------
FROM nginx:1.25-alpine

# Borramos configuración default de Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copiamos la configuración perzonalizada
COPY nginx.conf /etc/nginx/conf.d/

# Copiamos los archivos compilados del stage 1
COPY --from=builder /app/dist /usr/share/nginx/html

# Copiamos el archivo proxy para inyectar entorno en tiempo real
COPY entrypoint.sh /usr/share/nginx/entrypoint.sh

# Modificamos permisos para ejecutar Nginx y el Entrypoint como usuario NO root
RUN chown -R nginx:nginx /usr/share/nginx/html && \
    chmod -R 755 /usr/share/nginx/html && \
    chmod +x /usr/share/nginx/entrypoint.sh && \
    chown -R nginx:nginx /var/cache/nginx && \
    chown -R nginx:nginx /var/log/nginx && \
    chown -R nginx:nginx /etc/nginx/conf.d && \
    touch /var/run/nginx.pid && \
    chown -R nginx:nginx /var/run/nginx.pid && \
    chown nginx:nginx /usr/share/nginx/entrypoint.sh

# Usamos el usuario menos privilegiado disponible en la imagen nginx alpine
USER nginx

# Exponemos un puerto sin privilegios (>1024)
EXPOSE 8080

ENTRYPOINT ["/usr/share/nginx/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
