server {
    listen       8080;
    server_name  localhost;

    # Compresión gzip para optimizar los tiempos de carga
    gzip on;
    gzip_min_length 1000;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Headers estándar de seguridad
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";
    add_header Referrer-Policy "strict-origin-when-cross-origin";

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Configuración vital para soportar Vue Router History Mode (SPA)
        try_files $uri $uri/ /index.html;
    }

    # Bloquear el acceso a archivos ocultos (ej. ".git") por si algo se escapa en build
    location ~ /\. {
        deny all;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
