FROM node:20

# Crear carpeta de trabajo
WORKDIR /app

# Copiar package.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

# Exponer puerto (ajusta si usas otro)
EXPOSE 3000

# Comando de inicio
CMD ["npm", "run", "dev"]